### ISSUE TITLE
Exception: Call to a member function sL() on null

### ISSUE THREAD

**Issue by kitzberger** [itplusx/headless_gridelements#10]
With `2.0.2` I've got this exception now. Can't say why this is happening now and not before when working on #8 ;-/

![Bildschirmfoto vom 2021-07-28 12-04-58](https://user-images.githubusercontent.com/1405149/127304529-c780099c-e94f-4762-93a7-2a87bd8bb636.png)

**Comment by schloram** [comment]
Hi @kitzberger ,
thanks again.

I should have realized that when reviewing the PR. `$GLOBALS['LANG']` is only for backend or CLI purposes.

> Usually this is injected into $GLOBALS['LANG'] when in backend or CLI context, and populated by the current backend user. **Don't rely on $GLOBAL['LANG'] in frontend, as it is only available in certain circumstances!** In Frontend, this is also used to translate "labels", see TypoScriptFrontendController->sL() for that.

see: https://api.typo3.org/10.4/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_localization_1_1_language_service.html

This explains why it sometimes works and sometimes it doesn't.
